export const SAVE_AUDIENCE_REQUEST = 'SAVE_AUDIENCE_REQUEST';
export const SAVE_AUDIENCE_SUCCESS = 'SAVE_AUDIENCE_SUCCESS';
export const SAVE_AUDIENCE_FAILURE = 'SAVE_AUDIENCE_FAILURE';

export const FIND_AUDIENCE_REQUEST = 'FIND_AUDIENCE_REQUEST';
export const FIND_AUDIENCE_SUCCESS = 'FIND_AUDIENCE_SUCCESS';
export const FIND_AUDIENCE_FAILURE = 'FIND_AUDIENCE_FAILURE';

export const FIND_AUDIENCES_REQUEST = 'FIND_AUDIENCES_REQUEST';
export const FIND_AUDIENCES_SUCCESS = 'FIND_AUDIENCES_SUCCESS';
export const FIND_AUDIENCES_FAILURE = 'FIND_AUDIENCES_FAILURE';

export const FIND_TRANSACTION_REQUEST = 'FIND_TRANSACTION_REQUEST';
export const FIND_TRANSACTION_SUCCESS = 'FIND_TRANSACTION_SUCCESS';
export const FIND_TRANSACTION_FAILURE = 'FIND_TRANSACTION_FAILURE';

export const FIND_TRANSACTIONS_REQUEST = 'FIND_TRANSACTIONS_REQUEST';
export const FIND_TRANSACTIONS_SUCCESS = 'FIND_TRANSACTIONS_SUCCESS';
export const FIND_TRANSACTIONS_FAILURE = 'FIND_TRANSACTIONS_FAILURE';

export const SAVE_EO_REQUEST = 'SAVE_EO_REQUEST';
export const SAVE_EO_SUCCESS = 'SAVE_EO_SUCCESS';
export const SAVE_EO_FAILURE = 'SAVE_EO_FAILURE';

export const FIND_EO_REQUEST = 'FIND_EO_REQUEST';
export const FIND_EO_SUCCESS = 'FIND_EO_SUCCESS';
export const FIND_EO_FAILURE = 'FIND_EO_FAILURE';

export const FIND_EOS_REQUEST = 'FIND_EOS_REQUEST';
export const FIND_EOS_SUCCESS = 'FIND_EOS_SUCCESS';
export const FIND_EOS_FAILURE = 'FIND_EOS_FAILURE';

export const SAVE_EVENT_REQUEST = 'SAVE_EVENT_REQUEST';
export const SAVE_EVENT_SUCCESS = 'SAVE_EVENT_SUCCESS';
export const SAVE_EVENT_FAILURE = 'SAVE_EVENT_FAILURE';

export const FIND_EVENT_REQUEST = 'FIND_EVENT_REQUEST';
export const FIND_EVENT_SUCCESS = 'FIND_EVENT_SUCCESS';
export const FIND_EVENT_FAILURE = 'FIND_EVENT_FAILURE';

export const FIND_EVENTS_REQUEST = 'FIND_EVENTS_REQUEST';
export const FIND_EVENTS_SUCCESS = 'FIND_EVENTS_SUCCESS';
export const FIND_EVENTS_FAILURE = 'FIND_EVENTS_FAILURE';

export const FIND_STATUS_EVENTS_REQUEST = 'FIND_STATUS_EVENTS_REQUEST';
export const FIND_STATUS_EVENTS_SUCCESS = 'FIND_STATUS_EVENTS_SUCCESS';
export const FIND_STATUS_EVENTS_FAILURE = 'FIND_STATUS_EVENTS_FAILURE';

export const SAVE_MERCHANT_REQUEST = 'SAVE_MERCHANT_REQUEST';
export const SAVE_MERCHANT_SUCCESS = 'SAVE_MERCHANT_SUCCESS';
export const SAVE_MERCHANT_FAILURE = 'SAVE_MERCHANT_FAILURE';

export const FIND_MERCHANT_REQUEST = 'FIND_MERCHANT_REQUEST';
export const FIND_MERCHANT_SUCCESS = 'FIND_MERCHANT_SUCCESS';
export const FIND_MERCHANT_FAILURE = 'FIND_MERCHANT_FAILURE';

export const FIND_MERCHANTS_REQUEST = 'FIND_MERCHANTS_REQUEST';
export const FIND_MERCHANTS_SUCCESS = 'FIND_MERCHANTS_SUCCESS';
export const FIND_MERCHANTS_FAILURE = 'FIND_MERCHANTS_FAILURE';

export const FIND_EVENT_MERCHANTS_REQUEST = 'FIND_EVENT_MERCHANTS_REQUEST';
export const FIND_EVENT_MERCHANTS_SUCCESS = 'FIND_EVENT_MERCHANTS_SUCCESS';
export const FIND_EVENT_MERCHANTS_FAILURE = 'FIND_EVENT_MERCHANTS_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const RESTORE_TOKEN_REQUEST = 'RESTORE_TOKEN_REQUEST';
export const RESTORE_TOKEN_FAILURE = 'RESTORE_TOKEN_FAILURE';
export const RESTORE_TOKEN_SUCCESS = 'RESTORE_TOKEN_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const USER_CREDIT_REQUEST = 'USER_CREDIT_REQUEST';
export const USER_CREDIT_FAILURE = 'USER_CREDIT_FAILURE';
export const USER_CREDIT_SUCCESS = 'USER_CREDIT_SUCCESS';

export const USER_HISTORY_CREDIT_REQUEST = 'USER_HISTORY_CREDIT_REQUEST';
export const USER_HISTORY_CREDIT_FAILURE = 'USER_HISTORY_CREDIT_FAILURE';
export const USER_HISTORY_CREDIT_SUCCESS = 'USER_HISTORY_CREDIT_SUCCESS';

export const SAVE_TRANSACTION_REQUEST = 'SAVE_TRANSACTION_REQUEST';
export const SAVE_TRANSACTION_FAILURE = 'SAVE_TRANSACTION_FAILURE';
export const SAVE_TRANSACTION_SUCCESS = 'SAVE_TRANSACTION_SUCCESS';

export const FIND_USER_TRANSACTION_REQUEST = 'FIND_USER_TRANSACTION_REQUEST';
export const FIND_USER_TRANSACTION_FAILURE = 'FIND_USER_TRANSACTION_FAILURE';
export const FIND_USER_TRANSACTION_SUCCESS = 'FIND_USER_TRANSACTION_SUCCESS';

export const FIND_TICKETS_TRANSACTION_REQUEST =
  'FIND_TICKETS_TRANSACTION_REQUEST';
export const FIND_TICKETS_TRANSACTION_FAILURE =
  'FIND_TICKETS_TRANSACTION_FAILURE';
export const FIND_TICKETS_TRANSACTION_SUCCESS =
  'FIND_TICKETS_TRANSACTION_SUCCESS';

export const CHECK_TRANSACTION_REQUEST = 'CHECK_TRANSACTION_REQUEST';
export const CHECK_TRANSACTION_FAILURE = 'CHECK_TRANSACTION_FAILURE';
export const CHECK_TRANSACTION_SUCCESS = 'CHECK_TRANSACTION_SUCCESS';

export const FIND_CATEGORY_REQUEST = 'FIND_CATEGORY_REQUEST';
export const FIND_CATEGORY_FAILURE = 'FIND_CATEGORY_FAILURE';
export const FIND_CATEGORY_SUCCESS = 'FIND_CATEGORY_SUCCESS';
export const EVENTS_STATUS_ONPROGRESS_REQUEST =
  'EVENTS_STATUS_ONPROGRESS_REQUEST';
export const EVENTS_STATUS_ONPROGRESS_FAILURE =
  'EVENTS_STATUS_ONPROGRESS_FAILURE';
export const EVENTS_STATUS_ONPROGRESS_SUCCESS =
  'EVENTS_STATUS_ONPROGRESS_SUCCESS';

export const EVENTS_STATUS_ONSCHEDULE_REQUEST =
  'EVENTS_STATUS_ONSCHEDULE_REQUEST';
export const EVENTS_STATUS_ONSCHEDULE_FAILURE =
  'EVENTS_STATUS_ONSCHEDULE_FAILURE';
export const EVENTS_STATUS_ONSCHEDULE_SUCCESS =
  'EVENTS_STATUS_ONSCHEDULE_SUCCESS';

export const EVENTS_STATUS_DONE_REQUEST = 'EVENTS_STATUS_DONE_REQUEST';
export const EVENTS_STATUS_DONE_FAILURE = 'EVENTS_STATUS_DONE_FAILURE';
export const EVENTS_STATUS_DONE_SUCCESS = 'EVENTS_STATUS_DONE_SUCCESS';
